added 2 axis joystick for marlin cannon control and added a shoot button
AlexJanson/LekAanDek pull request #30
Opened 2021-05-16 22:48 UTC by Mitchell-T

If any of you know a cleaner way of doing this feel free to request changes

2021-05-17 08:04 UTC, AlexJanson requested changes

2021-05-17 08:04 UTC, AlexJanson commented on Assets/Scripts/Puzzles/Marlin/MarlinJoystick.cs
> +                        Debug.Log("uhhh this shouldn't be possible");
Please remove the debug log 🙂.

2021-05-17 08:19 UTC, AlexJanson approved these changes

2021-05-17 10:05 UTC, SjorsMaster requested changes
Tested: Not working as expected.
The joystick doesn't properly seem to get the rotation unless its pushed down into the panel.
This requires some tweaking.

2021-05-18 14:07 UTC, SjorsMaster approved these changes
Still requires some tweaking, the joystick starts in the air which is just out of range for the points. But it's a lot more usable than before.

2021-05-18 14:13 UTC, merged